### ISSUE TITLE
serialization/deserialization fails with certain values

### ISSUE THREAD

**Issue by cmastelaro** [msgpack/msgpack-c#1004]
Guys, i've been trying to serialize some objects inside a std::vector and i'm getting odd results and crashes (bad_cast) when deserializing.

Here is the complementary classes to serialize

```
class WndPosition
{
public:
    WndPosition() {};
    WndPosition(int32_t _x, int32_t _y) :
        x(_x), y(_y) {};
    WndPosition(const WndPosition & pos) {
      x = pos.x;
      y = pos.y;
    };

    int32_t x;
    int32_t y;
    MSGPACK_DEFINE(x, y);
};

class WndPlacement
{
public:
    WndPlacement() {};
    WndPlacement(long t, long l, long r, long b) :
        top(t), left(l), right(r), bottom(b) {};
    WndPlacement(const WndPlacement & place) {
        top = place.top;
        left = place.left;
        right = place.right;
        bottom = place.bottom;
    };

    long top;
    long left;
    long right;
    long bottom;

    MSGPACK_DEFINE(top, left, right, bottom);
};

class WndGeoItem
{
public:
    WndGeoItem() {};
    WndGeoItem(std::string n, std::string p, bool i, uint32_t l, uint32_t f, uint32_t c, WndPosition _max, WndPosition _min, WndPlacement _normal) :
        name(n), path(p), open(i), length(l), flags(f), cmds(c), max(_max), min(_min), normal(_normal) {};

    std::string name;
    std::string path;
    bool open;
    uint32_t length;
    uint32_t flags;
    uint32_t cmds;
    WndPosition max;
    WndPosition min;
    WndPlacement normal;

    MSGPACK_DEFINE(name, path, open, length, flags, cmds, max, min, normal);
};
```
And then i'm trying to serialize them into a vector

```
void serializeTest()
{
    msgpack::sbuffer buffer;
    msgpack::packer<msgpack::sbuffer> packer(buffer);

    WndPosition max(-8, -31);
    WndPosition min(-1, -1);
    WndPlacement place(1, 768, 1044, 320);
    WndGeoItem i("ABU", "AJU.jcdn", false, 44, 2, 3, max, min, place);

    std::vector<WndGeoItem> items;
    items.push_back(i);
    items.push_back(i);

    packer.pack(items);

    std::ofstream ofs("input.txt", std::ofstream::out);
    ofs.write(buffer.data(), buffer.size());
    ofs.close();

    msgpack::sbuffer sbuff;
    std::ifstream ifs("input.txt", std::ifstream::in);
    std::stringstream ss;
    ss << ifs.rdbuf();

    msgpack::unpacker upk;
    upk.reserve_buffer(ss.str().size());
    memcpy(upk.buffer(), ss.str().data(), ss.str().size());
    upk.buffer_consumed(ss.str().size());

    std::vector<WndGeoItem> out;
    msgpack::object_handle result;
    upk.next(result);
    msgpack::object obj = result.get();
    obj.convert(out);
}

```

And where is the odd behavior ??!

Here it is,... notice the values of WndPlacement object, if you put the value 26 (exactly 26) on any parameter of WndPlacement object it will crash on deserialize with bad_cast, and tell us that is not an array serialized !!!!...  the value 26 is a cabalistic number ?!?!

`WndPlacement place(1, 768, 1044, 320);`

It's very simple to reproduce and maibe a serious issue for msgpack implementation.

TO REPRODUCE:
Use the same code above and replace
`WndPlacement place(1, 768, 1044, 320); `
with
`WndPlacement place(1, 768, 1044, 26);`
or any position you want !! but the value 26 on any position will give us a bad_cast deserialization issue !!!

**Comment by redboltz** [comment]
The code is too big. Could you post https://stackoverflow.com/help/minimal-reproducible-example ?

In addition, printing msgpack::object would help you. 
bad_cast is typically happens in convert() or as(). You can print `obj` before calling them

```cpp
std::cout << obj << std::endl;
```

Using `msgpack::unpack()` function instead of `msgpack::unpacker` would also be helping analysing. You can observe the -same/different behavior.

**Comment by cmastelaro** [comment]
Good to know !

what's your msgpack version ?!?

**Comment by redboltz** [comment]
4.1.0. b350a00f6bf2507702eaafcf92659e634f64264

**Comment by cmastelaro** [comment]
Same error packing a single integer with the damn 26 value........ all other values works !!!!

```
    msgpack::sbuffer buffer;
    msgpack::packer<msgpack::sbuffer> packer(buffer);

    int a = 26; /* cabalistic number !!!! , try with 25...13442...43534634....works fine...*/
    packer.pack(a);

    std::ofstream ofs("input.txt", std::ofstream::out);
    ofs.write(buffer.data(), buffer.size());
    ofs.close();

    std::ifstream ifs("input.txt", std::ifstream::in);
    std::stringstream ss;
    ss << ifs.rdbuf();

    msgpack::unpacker upk;
    upk.reserve_buffer(ss.str().size());
    memcpy(upk.buffer(), ss.str().data(), ss.str().size());
    upk.buffer_consumed(ss.str().size());

    msgpack::object_handle result;
    upk.next(result);
    msgpack::object obj = result.get();
    std::cout << obj << std::endl;
    int d;
    obj.convert(d);
```

**Comment by redboltz** [comment]
What kind of output you got at `std::cout << obj << std::endl;` ?

Anyway, try remove file access from your code.

```cpp
msgpack::object_handle result = msgpack::unpack(sbuffer.data(), sbuffer.size());
```

This is one way to create minimal code.

**Comment by cmastelaro** [comment]
great !! it works !

i was so focused on packing things that i've not notice the reading buffer error !

Thank you for your help ! i appreciate that !

i'll close the ticket

**Comment by redboltz** [comment]
You are welcome.

By the way, I recommend that **binary** dump "input.txt".
https://github.com/msgpack/msgpack/blob/master/spec.md#int-format-family
26 is packed (encoded) as positive fixint. The packed value is 26 (decimal).
It is EOF. It seems that you open the file as text mode.
See https://en.cppreference.com/w/cpp/io/basic_ofstream/basic_ofstream

MessagePack is a binary format. The file opened as text mode does not work well with the binary data. That is the reason for the issue.
If you omit the binary/text mode setting, I guess that the default mode is applied, and the default mode depends on the environment. That is the reason that your code works well on my environment.

If you write minimal and complete code, during that step, you might notice the behavior is changed. And noticed that the issue is not in msgpack-c but in your code by yourself. It is usually efficient approach to solve the issue.
That is the reason I **strongly** requested minimal and complete code.

When you report another issue in the future, please post minimal and complete code before you doubt msgpack-c code.
I always do it when I meet suspicious behavior on some open source library.
