### ISSUE TITLE
What is the minimum Boost install

### ISSUE THREAD

**Issue by MyraBaba** [msgpack/msgpack-c#1063]
Boost install almost 560Mb

what is the required boost lib to install ? and the command ?

Best

**Comment by redboltz** [comment]
https://github.com/msgpack/msgpack-c/issues/978#issuecomment-921537031

Here is the list of boost required packages. Actual command is different for each environment.
The simplest approach is download boost and add include path `boost_1_81_0/include` to your project.
You don't need to build boost because msgpack-c (C++) uses only header-only part of the boost.
