### ISSUE TITLE
[Question/Discussion] msgpack is much slower than Boost.JSON

### ISSUE THREAD

**Issue by DUOLabs333** [msgpack/msgpack-c#1106]
I'm currently in the process of trying out msgpack to see if it can replace JSON as my messaging format (Boost.JSON is pretty fast, but not enough for the latency to be low). msgpack is binary, so it should be at least as fast as JSON. However, to my surprise, it is VERY slow, even slower than nlohmann::json. I'm surely doing something wrong, so here's my workflow: I have a `std::map<variant, variant>`, with the key always being a string, and the value being vectors of variants, other maps, float, ints, and so on. I'm then packing, sending it, then unpacking it. Here's the relevant transmission code:

```c++
void serializeInt(std::array<uint8_t,4>& buf, uint32_t val) { //Assumes that val is a 32-bit number (almost always true). Serializes in little endian in endian-agnostic way
    buf[0] = (val) & 0xFF;
    buf[1] = (val >> 8) & 0xFF;
    buf[2] = (val >> 16) & 0xFF;
    buf[3] = (val >> 24) & 0xFF;
}

uint32_t deserializeInt(std::array<uint8_t,4>& buf){ //Deserialzes from little endian in endian-agnostic way
    return buf[0] | (buf[1] << 8) | (buf[2] << 16) | (buf[3] << 24);
}

bool always_reference(msgpack::type::object_type, std::size_t, void *){
    return true;
}

json::map readFromConn(){

    auto curr=currStruct();
    
    asio::error_code ec;
    asio::read(*(curr->conn), asio::buffer(curr->size_buf,4), asio::transfer_exactly(4), ec);
    if (ec){
        throw RWError(ec);
    }
    
    auto msg_size=deserializeInt(curr->size_buf);
    
    if (curr->data_buf!=NULL){
        free(curr->data_buf);
    }
    
    curr->data_buf=(char*)malloc(msg_size);
    
    asio::read(*(curr->conn), asio::buffer(curr->data_buf, msg_size), asio::transfer_exactly(msg_size), ec);
    if (ec){
        throw RWError(ec);
    }
    
    msgpack::unpack(curr->handle, curr->data_buf, msg_size, always_reference);
    
    return curr->handle.get().as<json::map>();
}

void writeToConn(json::map& json){
    json["uuid"]=uuid;
    
    auto curr=currStruct();
    auto stream = std::stringstream();
    
    msgpack::pack(stream, json); 
    
    auto data=stream.str();
    
    serializeInt(curr->size_buf, data.size());
    
    asio::error_code ec;
    asio::write(*(curr->conn), asio::buffer(curr->size_buf, 4), ec);
    if (ec){
        throw RWError(ec);
    }
    
    asio::write(*(curr->conn), asio::buffer(data), ec);
    if (ec){
        throw RWError(ec);
    }
}
```

**Comment by redboltz** [comment]
I'm not sure why. But I prepared measuring code example.
You can replate `data` with your actual type.

Here is an example code to measure time:

## pack, unpack, convert(no variant type)
```cpp
#include <iostream>
#include <chrono>
#include <string>
#include <vector>

#include <msgpack.hpp>

namespace mp = msgpack;

inline bool always_reference(msgpack::type::object_type, std::size_t, void *){
    return true;
}

int main() {
    std::vector<std::tuple<int, double, std::string>> data;
    for (int i = 0; i != 10000; ++i) {
        data.emplace_back(12, 34.56, "hello");
    }
    auto start_pack = std::chrono::steady_clock::now();
    mp::sbuffer sb;
    mp::pack(sb, data);
    auto end_pack = std::chrono::steady_clock::now();
    std::cout << "pack: "
              << std::chrono::duration_cast<std::chrono::microseconds>(end_pack - start_pack).count()
              << " us" << std::endl;
    std::cout << "sb address:         " << static_cast<void const*>(sb.data()) << std::endl;
    auto start_unpack = std::chrono::steady_clock::now();
    auto oh = mp::unpack(sb.data(), sb.size(), always_reference);
    auto end_unpack = std::chrono::steady_clock::now();
    std::cout << "unpack: "
              << std::chrono::duration_cast<std::chrono::microseconds>(end_unpack - start_unpack).count()
              << " us" << std::endl;
    auto start_convert = std::chrono::steady_clock::now();
    auto const& data2 = oh->as<std::vector<std::tuple<int, double, std::string_view>>>();
    auto end_convert = std::chrono::steady_clock::now();
    std::cout << "convert: "
              << std::chrono::duration_cast<std::chrono::microseconds>(end_convert - start_convert).count()
              << " us" << std::endl;
    std::cout << std::get<2>(data2[0]) << std::endl;
    std::cout << "1st string address: " << static_cast<void const*>(std::get<2>(data2[0]).data()) << std::endl;
}
```

Result on my environment:

```
pack: 165 us
sb address:         0x5beabd1c98d0
unpack: 789 us
convert: 325 us
hello
1st string address: 0x5beabd1c98df
```

It doesn't use `msgpack::type::variant_ref`.

The second example is using `msgpack::type::variant_ref`.

## pack, unpack, convert(variant type)

```cpp
#include <iostream>
#include <chrono>
#include <string>
#include <vector>

#include <msgpack.hpp>

namespace mp = msgpack;

inline bool always_reference(msgpack::type::object_type, std::size_t, void *){
    return true;
}

int main() {
    std::vector<std::tuple<int, double, std::string>> data;
    for (int i = 0; i != 10000; ++i) {
        data.emplace_back(12, 34.56, "hello");
    }
    auto start_pack = std::chrono::steady_clock::now();
    mp::sbuffer sb;
    mp::pack(sb, data);
    auto end_pack = std::chrono::steady_clock::now();
    std::cout << "pack: "
              << std::chrono::duration_cast<std::chrono::microseconds>(end_pack - start_pack).count()
              << " us" << std::endl;
    std::cout << "sb address:         " << static_cast<void const*>(sb.data()) << std::endl;
    auto start_unpack = std::chrono::steady_clock::now();
    auto oh = mp::unpack(sb.data(), sb.size(), always_reference);
    auto end_unpack = std::chrono::steady_clock::now();
    std::cout << "unpack: "
              << std::chrono::duration_cast<std::chrono::microseconds>(end_unpack - start_unpack).count()
              << " us" << std::endl;
    auto start_convert = std::chrono::steady_clock::now();
    auto const& vr = oh->as<mp::type::variant_ref>();
    auto end_convert = std::chrono::steady_clock::now();
    std::cout << "convert: "
              << std::chrono::duration_cast<std::chrono::microseconds>(end_convert - start_convert).count()
              << " us" << std::endl;
    std::cout << vr.as_vector()[0].as_vector()[2].as_boost_string_ref() << std::endl;
    std::cout << "1st string address: " << &vr.as_vector()[0].as_vector()[2].as_boost_string_ref() << std::endl;
}
```

Result on my environment:

```
pack: 161 us
sb address:         0x5ec8c579c8d0
unpack: 811 us
convert: 3945 us
hello
1st string address: 0x5ec8c58cb4e8
```

## Observation
pack and unpack is similar result because they are no difference.
convert to `msgpack::type::variant` is slower than original type (replaced string with string_view).
Both no string copy is happened.

## Environment
clang version 16.0.6

```
clang++ -O3 sample.cpp
```

**Comment by DUOLabs333** [comment]
Did I overlook something? Your second test doesn't use `variant`.

**Comment by redboltz** [comment]
> Did I overlook something? Your second test doesn't use `variant`.

Sorry, I fixed the comment.

**Comment by DUOLabs333** [comment]
I know what the problem is (I accidentally recreated it with Boost.JSON, so it's not unique to msgpack) --- sending `4` bytes (to get the size) with asio is slow (maybe some sort of caching/buffering)?

**Comment by DUOLabs333** [comment]
I figured out the reason --- disabling Nagle's algorithm fixes the problem.

**Comment by redboltz** [comment]
> I figured out the reason --- disabling Nagle's algorithm fixes the problem.

Thank you for reporting.
I also experienced the same issue. Maybe you mean https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/ip__tcp/no_delay.html 

For the next time you would report the issue, please separate network (asio) part from msgpack-c part. It helps to figure out where the problem is. Like my code exapmle.

By the way, msgpack-c (C++) doesn't have custom allocator. msgpack-c uses C++ `new` and C `malloc`. The reason using malloc is for realloc. C++ doesn't have realloc like functionality. I know Boost.Container has it but it contains custom malloc libraray. msgpack-c has no boost mode, it is difficult to use.
(Many users said that msgpack-c should work without boost. I have different opinion, I personally respect boost very much. But no boost mode helps many people)

So I think that providing custom allocator is a practical solution. At least unpacker, zone, sbuffer has memory allocation code. The use new or malloc. When msgpack-c has custom allocator injection functionality, msgpack-c would be work higher speed. Allocation strategy depends on application. So custom allocator is good.
However, I don't have much time (and motivation) to implement custom allocator, so far.
If anyone seriously want to have it, I would request creating a pull request to them.

As far as my experience, msgpack-c allocator speed is usually not a dominant part of cost. For example, netowork communication application usually has different bottle neck.

**Comment by DUOLabs333** [comment]
Oh, sorry --- I changed my comment when I realized that it had nothing to do with malloc (and the malloc in any case was on my side).
