### ISSUE TITLE
Wrong unpack_error constructor for MSGPACK_USE_CPP03

### ISSUE THREAD

**Issue by ecorm** [msgpack/msgpack-c#174]
In unpack.hpp, at this [line](https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/unpack.hpp#L825), there's a NOT operator missing. It should be:
```
#if !defined(MSGPACK_USE_CPP03)
```

**Comment by redboltz** [comment]
The original code when @ecom pointed out is here:
```C++
struct unpack_error : public std::runtime_error {
#if defined(MSGPACK_USE_CPP03)
    unpack_error(const std::string& msg) :
        std::runtime_error(msg) { }
#else
    unpack_error(const char* msg) :
        std::runtime_error(msg) { }
#endif
};
```

https://github.com/msgpack/msgpack-c/blob/2d61fdf8651c6f75f5f2b1d19e309ab904f6c21b/include/msgpack/unpack.hpp#L825

const char* version constructor have been introduced since C++11. const std::string& version exists in both C++03 and C++11.
See:
http://www.cplusplus.com/reference/stdexcept/runtime_error/

So, NOT operator is not needed.

However, C++11 version of runtime_error supports both const char* and const std::string& versions of constructors. So the code should be as follows:

```C++
struct unpack_error : public std::runtime_error {
    unpack_error(const std::string& msg) :
        std::runtime_error(msg) { }
#if !defined(MSGPACK_USE_CPP03)
    unpack_error(const char* msg) :
        std::runtime_error(msg) { }
#endif
};
```

And current code has been fixed.

See:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/unpack.hpp#L66

So I close the issue.
