### ISSUE TITLE
exists old namespace

### ISSUE THREAD

**Issue by nori0428** [msgpack/msgpack-c#186]
msgpack::type exists in some files.
> s/msgpack::type/msgpack::v1::type/g?

* include/msgpack/adaptor/nil.hpp
```
msgpack::type::nil v;
```
* include/msgpack/adaptor/detail/cpp03_define.hpp
* include/msgpack/adaptor/detail/cpp11_define.hpp
```
#define MSGPACK_DEFINE(...) \
    template <typename Packer> \
    void msgpack_pack(Packer& pk) const \
    { \
        msgpack::type::make_define(__VA_ARGS__).msgpack_pack(pk); \
    } \
    void msgpack_unpack(msgpack::object const& o) \
    { \
        msgpack::type::make_define(__VA_ARGS__).msgpack_unpack(o); \
    }\
    template <typename MSGPACK_OBJECT> \
    void msgpack_object(MSGPACK_OBJECT* o, msgpack::zone& z) const \
    { \
        msgpack::type::make_define(__VA_ARGS__).msgpack_object(o, z); \
    }
```

* include/msgpack/adaptor/detail/cpp03_msgpack_tuple.hpp  
But commented out.any intended?

**Comment by nori0428** [comment]
BTW,
Thanks to fix https://github.com/msgpack/msgpack-c/issues/149 and related to.;)

**Comment by redboltz** [comment]
I think that they should be type::nil and type::make_define...
Because the types are part of the v1 implementation. If it's not, it should be msgpack::type::some_types.
Minimizing explicit versioning makes code maintenance easier.

msgpack::type::tuple should be type::tuple. The reason those codes are commented out, the original codes are commented out. I don't know why, but I just keep the original code.

**Comment by nori0428** [comment]
Thanks for rapid reply.
I agree about type::nil and understood about msgpack::type::tuple.

But MSGPACK_DEFINE is a MACRO.I think that it's difficult to use type::make_define.
an example shows following.
```
#include "msgpack/msgpack.hpp"

namespace MyApp {

struct Foo {
  int a;

  MSGPACK_DEFINE(a);
}

} // namespace MyApp
```

Do we have to use MSGPACK_API_VERSION_NAMESPACE when using MSGPACK_DEFINE?

**Comment by nori0428** [comment]
Ah, sorry.
I‘m something wrong... example/class_instrusive.cpp works fine.
I check my code.

**Comment by redboltz** [comment]
Ah, I remembered my decision. 
Because of MACRO, MSGPACK_DEFINE is NOT a part of v1 interface. It is a common interface. So it uses msgpack::type::* intentionally. When clients uses MSGPACK_DEFINE, default or explicitly selected version of make_define is used.

I think that it is a reasonable design choice.

> Do we have to use MSGPACK_API_VERSION_NAMESPACE when using MSGPACK_DEFINE?
No.

See:
```C++
#include <sstream>
#include <msgpack.hpp>

struct S {
    int i;
    MSGPACK_DEFINE(i);
};

int main() {
    std::stringstream ss;
    S s;
    msgpack::pack(ss, s);
    assert(msgpack::unpack(ss.str().data(), ss.str().size()).get().as<S>().i == s.i);
}
```

**Comment by nori0428** [comment]
Thanks, this was my mistake.I'm sorry for troubling you.
