### ISSUE TITLE
Troubleshooting Tips

### ISSUE THREAD

**Issue by davidchappelle** [msgpack/msgpack-c#204]
I have run into this issue a few times now.

```
enum foo {
bar
};
MSGPACK_ADD_ENUM(foo)
```

Then I try and create an object as follows:

```
msgpack::object obj(foo::bar);
```

I get a spew of error messages from the compiler:

```
/usr/local/include/msgpack/object.hpp:497:5: error: no matching function for call to 'operator<<'
    msgpack::operator<<(*this, v);
    ^~~~~~~~~~~~~~~~~
```

Now it turns out that since an enum is a custom msgpack type it requires you to also provide a msgpack::zone to the msgpack::object consructor as follows:

```
msgpack::zone zone;
msgpack::object obj(foo::bar, &zone);
```

This is really annoying to track down and I don't see any obvious documentation to help one come to this conclusion. Can we add this somewhere o perhaps even relax the constraint that a zone is required to use an enum as a custom type?

**Comment by redboltz** [comment]
Thank you for reporting the issue. There is some documentation about user types to msgpack::object conversion as follows:
https://github.com/msgpack/msgpack-c/wiki/cpp_object#conversion

I thought that converting to msgpack::object from any types uses always msgpack::object::with_zone. msgpack::object::with_zone is internal type that is created by msgpack's constructor with zone.
See:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/object.hpp#L69
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/object.hpp#L508

However, that restriction is too much. If a converted type is not an array or a map of the msgpack, zone shouldn't be required.

So I updated the conversion logic. While updating, I found some problems about conversion operators.
The problems have been fixed in the PR https://github.com/msgpack/msgpack-c/pull/205
After applying the PR, you can convert enums to object with or without zone.

You need to write MSGPACK_ADD_ENUM after include msgpack_fwd.hpp and before include msgpack.hpp.
It is the same mannar as follows:
https://github.com/msgpack/msgpack-c/wiki/cpp_versioning#non-intrusive-approach

```C++
#include <msgpack_fwd.hpp>

enum class enumclass {
    elem
};

enum oldenum {
    elem
};

struct outer {
    enum class enumclass {
        elem
    };
    enum oldenum {
        elem
    };
};

MSGPACK_ADD_ENUM(enumclass);
MSGPACK_ADD_ENUM(oldenum);
MSGPACK_ADD_ENUM(outer::enumclass);
MSGPACK_ADD_ENUM(outer::oldenum);

// msgpack.hpp should be included after MSGPACK_ADD_ENUM(...)
#include <msgpack.hpp>

int main() {
    // without zone
    msgpack::object obj_ec(enumclass::elem);
    msgpack::object obj_oe(elem);
    msgpack::object obj_nest_ec(outer::enumclass::elem);
    msgpack::object obj_nest_oe(outer::elem);

    // with zone
    msgpack::zone z;
    msgpack::object obj_ec_z(enumclass::elem, z);
    msgpack::object obj_oe_z(elem, z);
    msgpack::object obj_nest_ec_z(outer::enumclass::elem, z);
    msgpack::object obj_nest_oe_z(outer::elem, z);
}
```

I will refine the documentation on the wiki.
