### ISSUE TITLE
[request] Tag new release

### ISSUE THREAD

**Issue by Pyrohh** [msgpack/msgpack-c#228]
Hello,

I was wondering if it'd be possible to tag a new release, as the last tag was quite a while ago, and there have been many fixes and improvements since then. I ask because we (or rather anatolik, as [mentioned here near the top of the comments](https://aur.archlinux.org/packages/msgpack/)) would like to package it in the Arch Linux repositories.

This is of course at your own accord, since I've no clue what things should be completed/fixed before a new release.

**Comment by anatol** [comment]
+1 for smaller and more often releases

**Comment by nobu-k** [comment]
It took time to release the new version because it's a major version up, which is one of a few chances to break compatibility, and we have been discussing how to deal with ABI compatibility issues of the header only library. However, we're planning to do the final work for the major version up on Tuesday next week. After that, we'll be able to release new versions more frequently as long as a new feature doesn't break ABI. Please stay tuned :)

**Comment by Pyrohh** [comment]
Thanks for the update @nobu-k!

**Comment by jpetso** [comment]
@redboltz @nobu-k Thank you for your constant and excellent work on msgpack-c! Congrats on the release :)

**Comment by Pyrohh** [comment]
Thank you @redboltz and @nobu-k, I'm surprised how much stuff you merged in a 24 hour period :)

I'll close this now.

**Comment by nobu-k** [comment]
We really appreciate all contributions. Please let us know if you find something wrong with the new version. Because it was almost midnight in Japan, I couldn't write a detailed release note. I'll write it as soon as possible.

**Comment by anatol** [comment]
Thanks for your great work!
