### ISSUE TITLE
Compilation error on Mac 10.9, with C++11, clang++

### ISSUE THREAD

**Issue by cloudveil** [msgpack/msgpack-c#244]
Just noticed an error when moving a personal project over to C++11:

/usr/local/include/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp(47): error: declaration of a member with the same name as its class

I found that simply commenting that line in cpp11_msgpack_tuple.hpp resolved the issue.

**Comment by redboltz** [comment]
Thank you for reporting the issue. 
The line that you got the error is a declaration of inheriting constructor. It has been supported since clang 3.3.

http://clang.llvm.org/cxx_status.html
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2540.htm

It is required to provide the constructors. If you comment out it, some tests wouldn't pass. But inheriting constructor should be
```C++
using base::base
```
Could you test it?

**Comment by cloudveil** [comment]
replacing line 47 with

    using base::base;

compiled and ran fine on this end.

**Comment by redboltz** [comment]
Thank you @cloudveil, I will send a PR soon.

**Comment by nobu-k** [comment]
Thank you for your report. I'll release the new version including this bug fix soon.
