### ISSUE TITLE
MSVC 2013 using obj.convert

### ISSUE THREAD

**Issue by thomasb0123** [msgpack/msgpack-c#272]
i got an error on compilation when i use : obj.convert(&a);

my code : 
						const char* test = datum[1].c_str();
						// qDebug() <<  "data to unserializ :for updateselfposition "  << test;
						std::vector<float> a = { 0, 0, 0 };
						//msgpack::pack(ss, a);
						msgpack::unpacked msg;
						msgpack::unpack(&msg, test, strlen(test));
						msgpack::object obj = msg.get();
						obj.convert(&a);
						float X = a.at(0);
						float Y = a.at(1);
						float Z = a.at(2);

Error	6	error LNK2001: unresolved external symbol "protected: virtual void __thiscall std::bad_cast::_Doraise(void)const " (?_Doraise@bad_cast@std@@MBEXXZ)	D:\Users\xxxxx\Documents\xxxx\xxxxx\Intermediate\ProjectFiles\TBTcpClientSocket.cpp.obj	TB

**Comment by redboltz** [comment]
Hi @thomasb0123.
If you are using msgpack-c version 1.0.0 or later, it is a header only library. And your error is occurred at linking. msgpack-c is just inherits std::bad_cast. See https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/object_fwd.hpp#L141

I'm not sure about that error, but it seems that the error is caused by MSVC's runtime library mismatching. If you link two or more libraries, I recommend that unify those libraries compile options such as /MT, /MD, /MTd, and /MDd. Then recompile libraries.

You might already have multiple libraries that are compiled by the different compile option from the same source, then link the libraries that are compiled using the same compile option as you compile the target code.

**Comment by thomasb0123** [comment]
I have the last version, i have include this file only 1 time. i use UE4 and it doesn't want try/catch maybe i can comment all  throw msgpack::type_error(); ?

**Comment by thomasb0123** [comment]
Yes It works now!!! I removed try/catch and throws (at my own risk) but i control datum before using them!
 Thx for your time!
Thomas
