### ISSUE TITLE
build error example

### ISSUE THREAD

**Issue by molele2** [msgpack/msgpack-c#320]
I build global project for success! build example for one 
#include <msgpack/object.hpp>
#include <msgpack/iterator.hpp>
#include <msgpack/zone.hpp>
#include <msgpack/pack.hpp>
#include <msgpack/unpack.hpp>
#include <msgpack/sbuffer.hpp>
#include <msgpack/vrefbuffer.hpp>
#include <msgpack/version.hpp>
#include <msgpack/type.hpp>

#include <string>
#include <iostream>
#include <sstream>

int main(void){
    msgpack::type::tuple<int,bool,std::string> src(1,true,"example");

    std::stringstream buffer;
    msgpack::pack(buffer,src);

    buffer.seekg(0);
    std::string str(buffer.str());
    msgpack::unpacked result;
    msgpack::unpack(result,str.data(),str.size());

    msgpack::object deserialized = result.get();
    std::cout << deserialized << std::endl;

    msgpack::type::tuple<int,bool,std::string> dst;
    deserialized.convert(&dst);

    return 0;
}

usr/local/include/msgpack/adaptor/vector.hpp:84: error: #pragma GCC diagnostic not allowed inside functions
/usr/local/include/msgpack/adaptor/vector.hpp:85: error: #pragma GCC diagnostic not allowed inside functions
/usr/local/include/msgpack/adaptor/vector.hpp:89: error: #pragma GCC diagnostic not allowed inside functions

**Comment by molele2** [comment]
What #pragma gcc diagnostic?

**Comment by redboltz** [comment]
The purpose of `#pragma gcc diagnostic` is to suppress redundant warnings. I checked the error message. It seems that old gcc doesn't support it. It has been supported since gcc 4.6. So I need to insert a condition checking macro into https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/adaptor/vector.hpp#L83

I will send a pull request to fix the problem. 

By the way, what version of gcc are you using? For quick fix, just remove pragma stuff from https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/adaptor/vector.hpp#L83

**Comment by redboltz** [comment]
@molele2 , I sent a PR to fix the issue. Could you try #322 ?

**Comment by molele2** [comment]
@redboltz  thank you for me
