### ISSUE TITLE
msgpack.dll doesn't export most of the functions

### ISSUE THREAD

**Issue by pi-jas** [msgpack/msgpack-c#356]
I'm trying to create a version of msgpack.dll to include in a LabVIEW VI but there only appear to be 33 functions which are prefaced with the MSGPACK_DLLEXPORT keyword. This is my first time using a DLL, so my understanding may be flawed.

My question is two-fold;
1. Am I doing something wrong?
2. How can I access functions such as msgpack_sbuffer_init, msgpack_packer_init and any of the msgpack_pack_xxx functions without having to modify the msgpack source?

Regards, John

**Comment by redboltz** [comment]
Hi @pi-jas, 

> 1. Am I doing something wrong?

No, you are doing well.

> 2. How can I access functions such as msgpack_sbuffer_init, msgpack_packer_init and any of the msgpack_pack_xxx functions without having to modify the msgpack source?

Those functions are defined as inline function. See:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sbuffer.h#L41
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/pack.h#L131
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/pack.h#L116

When you include those header files, you can call those functions. That's why, those functions are not exported to DLL.

FYI: When you use MSVC, 'inline' is replaced to '__inline'.
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L192

**Comment by pi-jas** [comment]
Thanks for the quick reply @redboltz.
It would seem that my problems lie in importing the DLL to LabVIEW. I guess I'll need to manually create the references from within LabVIEW to use the inline functions.

**Comment by pi-jas** [comment]
Just in case anyone else encounters the same problem. I solve the LabVIEW problem by writing a C wrapper around the static __inline functions to export them. 

<code>
__declspec(dllexport) 
void msgpack_sbuffer_init_ext(msgpack_sbuffer* sbuf)
{
	msgpack_sbuffer_init(sbuf);
}
</code>

I created a companion header file as well for completeness.
