### ISSUE TITLE
Feature request - Support Bare-Metal Platforms

### ISSUE THREAD

**Issue by clarkli86** [msgpack/msgpack-c#369]
Hi guys,

Thanks a lot for the great work on this library. I like it very much on Linux/Windows, so I would like to use it on bare-metal platforms, too. Have you guys thought about supporting targets like IAR and/or arm-none-eabi-gcc?

**Comment by redboltz** [comment]
Hi @clarkli86, I don't have much about IAR and arm-none-eabi-gcc. But I think that just cross-compile msgpack-c or compile msgpack-c on the target platform is enough. I'm using msgpack-c on rapspberry-pi that is arm architecture.

Could you tell me what the problem is to support IAR and arm-none-eabi-gcc?

**Comment by clarkli86** [comment]
Hi @redboltz ,
msgpack-c uses headers that are specific to Linux or Windows like <arpa/inet.h> to do endian swapping. Such headers are not available in a bare-metal target toolchain.

I assume you are using msgpack-c on pi with Linux?

Cheers,
Clark

**Comment by redboltz** [comment]
> I assume you are using msgpack-c on pi with Linux?

Yes.
I don't have bare-metal target toolchain.

> msgpack-c uses headers that are specific to Linux or Windows like to do endian swapping. 

If the only proglem is endian swapping, all we need to fix is sysdep.h

https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L87

Could you replace the following code 
```C++
#ifdef MSGPACK_ENDIAN_LITTLE_BYTE

#   ifdef _WIN32
#       if defined(ntohs)
#       define _msgpack_be16(x) ntohs(x)
#        elif defined(_byteswap_ushort) || (defined(_MSC_VER) && _MSC_VER >= 1400)
#            define _msgpack_be16(x) ((uint16_t)_byteswap_ushort((unsigned short)x))
#        else
#            define _msgpack_be16(x) ( \
                 ((((uint16_t)x) <<  8) ) | \
                 ((((uint16_t)x) >>  8) ) )
#        endif
#   else
#        define _msgpack_be16(x) ntohs(x)
#   endif

#   ifdef _WIN32
#        if defined(ntohl)
#            define _msgpack_be32(x) ntohl(x)
#        elif defined(_byteswap_ulong) || (defined(_MSC_VER) && _MSC_VER >= 1400)
#            define _msgpack_be32(x) ((uint32_t)_byteswap_ulong((unsigned long)x))
#        else
#            define _msgpack_be32(x) \
                 ( ((((uint32_t)x) << 24)               ) | \
                   ((((uint32_t)x) <<  8) & 0x00ff0000U ) | \
                   ((((uint32_t)x) >>  8) & 0x0000ff00U ) | \
                   ((((uint32_t)x) >> 24)               ) )
#        endif
#   else
#        define _msgpack_be32(x) ntohl(x)
#   endif

#   if defined(_byteswap_uint64) || (defined(_MSC_VER) && _MSC_VER >= 1400)
#        define _msgpack_be64(x) (_byteswap_uint64(x))
#   elif defined(bswap_64)
#        define _msgpack_be64(x) bswap_64(x)
#   elif defined(__DARWIN_OSSwapInt64)
#        define _msgpack_be64(x) __DARWIN_OSSwapInt64(x)
#   else
#        define _msgpack_be64(x) \
             ( ((((uint64_t)x) << 56)                         ) | \
               ((((uint64_t)x) << 40) & 0x00ff000000000000ULL ) | \
               ((((uint64_t)x) << 24) & 0x0000ff0000000000ULL ) | \
               ((((uint64_t)x) <<  8) & 0x000000ff00000000ULL ) | \
               ((((uint64_t)x) >>  8) & 0x00000000ff000000ULL ) | \
               ((((uint64_t)x) >> 24) & 0x0000000000ff0000ULL ) | \
               ((((uint64_t)x) >> 40) & 0x000000000000ff00ULL ) | \
               ((((uint64_t)x) >> 56)                         ) )
#   endif
```

with the following code on your environment?

```C++

#ifdef MSGPACK_ENDIAN_LITTLE_BYTE

#            define _msgpack_be16(x) ( \
                 ((((uint16_t)x) <<  8) ) | \
                 ((((uint16_t)x) >>  8) ) )
#            define _msgpack_be32(x) \
                 ( ((((uint32_t)x) << 24)               ) | \
                   ((((uint32_t)x) <<  8) & 0x00ff0000U ) | \
                   ((((uint32_t)x) >>  8) & 0x0000ff00U ) | \
                   ((((uint32_t)x) >> 24)               ) )
#        define _msgpack_be64(x) \
             ( ((((uint64_t)x) << 56)                         ) | \
               ((((uint64_t)x) << 40) & 0x00ff000000000000ULL ) | \
               ((((uint64_t)x) << 24) & 0x0000ff0000000000ULL ) | \
               ((((uint64_t)x) <<  8) & 0x000000ff00000000ULL ) | \
               ((((uint64_t)x) >>  8) & 0x00000000ff000000ULL ) | \
               ((((uint64_t)x) >> 24) & 0x0000000000ff0000ULL ) | \
               ((((uint64_t)x) >> 40) & 0x000000000000ff00ULL ) | \
               ((((uint64_t)x) >> 56)                         ) )
#   endif
```

If it works well, the next step is adding environment detection #if macro.

**Comment by mikapak** [comment]
Hi Redboltz,
I am also using bare metal target tool chain.
Replaced the above code.
Do I need to define MSGPACK_ENDIAN_LITTLE_BYTE in sysdep.h.

What is environment detection #if macro and how to define that

**Comment by redboltz** [comment]
MSGPACK_ENDIAN_LITTLE_BYTE  is from BOOST_ENDIAN_LITTLE_BYTE. Just replaced prefix from BOOST to MSGPACK.

See https://github.com/boostorg/predef/blob/1e8d1c2cfcac343305e2182f665742b9e38f7452/include/boost/predef/other/endian.h
http://www.boost.org/libs/endian/doc/index.html

I use Boost.Predef to detect the endian. http://www.boost.org/libs/predef/doc/html/predef/reference/other_macros.html#predef.reference.other_macros.boost_endian

Because, re-inventing endian detection code is wasteful, and Boost is known as widely used and supports various platform.

If Boost.Predef doesn't detect and you know the endian of your envitonment, you can define MSGPACK_ENDIAN_LITTLE_BYTE . However, I'm not 100% sure. Please refer to Boost.Predef's document and code.

BTW,

I wrote

```cpp
#ifdef MSGPACK_ENDIAN_LITTLE_BYTE
```

at that time. But the code is updated as
```cpp
#if MSGPACK_ENDIAN_LITTLE_BYTE
```

See
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L86

**Comment by clarkli86** [comment]
Hi @redboltz ,

Thanks for your reply. Unfortunately there are probably more than one place to be modified for bare-metal support. With your patch it did go further but stopped again at other system dependencies.
```
arm-none-eabi-g++   -marm -Wall -Werror -I../msgpack-c/include -std=c++1y -g -pg -c /home/clark/cpp/msgpack-none/main.cpp -o build/msgpack//home/clark/cpp/msgpack-none/main.o
In file included from ../msgpack-c/include/msgpack/vrefbuffer.hpp:15:0,
                 from ../msgpack-c/include/msgpack.hpp:16,
                 from /home/clark/cpp/msgpack-none/main.cpp:1:
../msgpack-c/include/msgpack/v1/vrefbuffer.hpp:26:21: fatal error: sys/uio.h: No such file or directory

```
main.cpp is a copy of the example at msgpack-c's homepage.

This is no longer an urgent feature needed by me. I suggest park it until there are more people begging for it :)

Cheers,
Clark

**Comment by starthal** [comment]
@clarkli86 The `sys/uio.h` error is because `vrefbuffer` references the `iovec` struct. But for `_WIN32` the struct is defined manually, and `readv()` and `writev()` are never called anyway.
```c
#ifndef _WIN32
#include <sys/uio.h>
#else
struct iovec {
    void  *iov_base;
    size_t iov_len;
};
#endif
```

I was able to get the build to work by

- disabling `-Werror` (due to warnings about using `char` as an array index)
- The `sysdep.h` patch above
- Unconditionally manually defining `struct iovec` in `vrefbuffer.h`

I think I will try this out in QEMU in the near future.
