### ISSUE TITLE
would be nice if msgpack can pack std::reference_wrapper

### ISSUE THREAD

**Issue by yongthecoder** [msgpack/msgpack-c#370]
msppack packs std::tuple<std::reference_wrapper<T>> but doesn't pack std::vector<std::reference_wrapper<T>>, or just std::reference_wrapper<T>

**Comment by redboltz** [comment]
Hi @yongthecoder, I considered supporting std::reference_wrapper.
There are five adaprots to support new types. See https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_adaptor
They are convert, as, pack, object, and object_with_zone. For std::reference_wrapper, pack, object (depends on T), and object_with_zone should be supported. Convert and pack cannot be supported because std::reference_wrapper is a kind of reference type. So they can't hold any resources.

Here is an example implementation that I tried:

```C++
template <typename T>
struct as<std::reference_wrapper<T>, typename std::enable_if<msgpack::has_as<T>::value>::type> {
    std::reference_wrapper<T> operator()(msgpack::object const& o) const {
        return std::reference_wrapper<T>(o.as<T>()); // dangling reference!!
    }
};
```

It's dangerous. I will support pack, object, and object_with_zone for std::reference_wrapper. Any ideas?

**Comment by yongthecoder** [comment]
Hi @redboltz, I think only supporting pack, object and object with zone should be OK, as char_ptr.hpp does. Thanks for your help!

**Comment by redboltz** [comment]
I just sent PR #373. Could you check it on your environment?
