### ISSUE TITLE
Converting to a tuple type silently hides error

### ISSUE THREAD

**Issue by sztomi** [msgpack/msgpack-c#390]
Consider the following code:

```cpp
    std::tuple<int, int, int> t;
    std::vector<int> vec{1, 2, 3, 4};

    msgpack::sbuffer sbuf;
    msgpack::pack(sbuf, vec);
    msgpack::unpacked msg;
    msgpack::unpack(&msg, sbuf.data(), sbuf.size());

    msgpack::object obj = msg.get();
    obj.convert(&t);
```

**What happens**: `t` will have 1, 2, 3 in it, but 4 is silently dropped. 
**What (I think) should happen**: `type_error` should be thrown.

**Comment by nobu-k** [comment]
This is an intentional behavior as you expected. It is used to implement serialization in a backward compatible way. For example, users can freely add a new element as a last element of tuple so that older versions of program can deserialize older elements without an error by ignoring the newly added element and the new version can successfully receive the new one. The new version can still deserialize the old format, too. Example use cases of this behavior are `MSGPACK_DEFINE` and serialization of arguments of RPC. Adding new fields or arguments at the end of existing ones is safe.

However, I also think it could be confusing to have such an implicit behavior on tuple and we should probably use a special type for that purpose. It's quite widely used now and changing the spec is difficult, though.

Any thoughts, @redboltz ?

**Comment by redboltz** [comment]
To be honest, I just implemented as same as original msgpack::tuple code https://github.com/msgpack/msgpack-c/blob/master/erb/cpp03_msgpack_tuple.hpp.erb#L164

I think that comparing using != is natural in C++. But it is worth having partial de-serialize functionality.

**Comment by sztomi** [comment]
Maybe keeping the original behavior would be better if that is the case. However, would it be possible to add a sort of (non-default) "strict" mode which would catch this and similar errors? For example:

    msgpack::unpack(&msg, sbuf.data(), sbuf.size()); // old behavior, no change
    msgpack::unpack(&msg, sbuf.data(), sbuf.size(), true); // new behavior, stricter error checking

Of course, this is not a trivial change, it would be necessary to pass the flag to each function that performs the unpacking. However, with a default parameter approach this can be done incrementally as well. Do you think this would be viable? If so, I would gladly take a look at implementing it.

**Comment by nobu-k** [comment]
I think that implementing a wrapper type of `std::tuple` whose `operator >>` strictly checks the size will solve the issue. So, we don't have to change any existing code.

**Comment by redboltz** [comment]
@nobu-k you mean something like `msgpack::strict_size_check<std::tuple>` ? I think it's good idea.

**Comment by nobu-k** [comment]
Yes. I think it'll be ok for most cases, but I don't know if it works with `MSGPACK_DEFINE`:

```
struct A {
  std::tuple<int, int> t;
  MSGPACK_DEFINE(can we use it here?);
};
```

**Comment by redboltz** [comment]
I sent the PR to fix the issue.

Currently, std::tuple and msgpack::type::tuple's size checking is wrong as @sztomi pointed out. If msgpack::object size is lager than the converted to container size, then it should be error. How about the opposite case? I think that it is OK to accept.
For example, msgpack::object is `[1,2,3]` and the converted to container is `std::tuple<int, int, int, int>`, the first three elements are stored to tuple.

If the class template `size_equal_only` is applied, the above case is error because size is not the same.

See https://github.com/redboltz/msgpack-c/blob/fix_390/test/size_equal_only.cpp#L82

@nobu-k, we can use `size_equal_only` with `MSGPACK_DEFINE`. See https://github.com/redboltz/msgpack-c/blob/fix_390/test/size_equal_only.cpp#L184

**Comment by redboltz** [comment]
> If msgpack::object size is lager than the converted to container size, then it should be error. 

It's not true. I forgot @nobu-k's comment https://github.com/msgpack/msgpack-c/issues/390#issuecomment-163411132
I will update my #390.

**Comment by redboltz** [comment]
@nobu-k, the current implementation doesn't satisfy backward compatibility.
See https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/adaptor/cpp11/tuple.hpp#L126
If the converted to container's size is larger than msgpack::object ARRAY's size, msgpack-c throws exception.

**Comment by redboltz** [comment]
By the way, that kind of tuple size check works on C++11 only. I mean `std::tuple` and `msgpack::type::tuple` on C++11. AFAIK, there is no way to get size of elements of `msgpack::type::tuple` on C++03. Because if you define the tuple as `msgpack::type::tuple<int, char>`, it is expanded to `msgpack::type::tuple<int, char, void, void, void>` total number of elements is always 32 by default. We cannot distinguish given template parameter with default paramater(void).

**Comment by redboltz** [comment]
> AFAIK, there is no way to get size of elements of msgpack::type::tuple on C++03. 

That's wrong. I found a way.

**Comment by redboltz** [comment]
I sent the PR #489. It fixes the issue.
This includes
* support converting to different size `msgpack::type::tuple` from ARRAY on C++03 and C++11.
* support converting to different size `std::tuple` from ARRAY on and C++11.
* add `msgpack::type::size_equal_only<T>` class template. If T's size is not the same as ARRAY's size, then msgpack::type_error() throws.
