### ISSUE TITLE
Invalid assignments from std::string to msgpack::object

### ISSUE THREAD

**Issue by davidchappelle** [msgpack/msgpack-c#417]
The following code compiles but for obvious reasons is incorrect due to the lack of a zone to properly allocate storage for the string.

```
#include <msgpack.hpp>
#include <string>

msgpack::object obj;

void set_procedure(const std::string procedure)
{
    obj = procedure;
}

int main(int argc, char** argv)
{
    set_procedure("foo");
    return 0;
}
```

**Comment by redboltz** [comment]
Thank you for reporting the issue. It is caused by the `adaptor::object` specialization for `std::string`. See https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/adaptor/string.hpp#L57. If I remove the specialization, then a compile error would occur as I expected.

The original code https://github.com/msgpack/msgpack-c/blob/cpp-0.5/src/msgpack/type/string.hpp#L51 has that conversion.

I think that the specialization is potentially dangerous. So I should remove the specialization. 

I'm not sure but some existing code might use the specialization intentionally and manage the std::string lifetime. I believe that it is rare case. Now we can choose remove the specialization from v1 (means both v1 and v2) or v2 only.

**Comment by redboltz** [comment]
I removed the specilization from only v2 namespace. It is the default on the version 2.x.
See #434
