### ISSUE TITLE
Incompatibility with older shared libraries

### ISSUE THREAD

**Issue by jamessan** [msgpack/msgpack-c#419]
It recently came up (in neovim/neovim#4108 and Debian bug [814096](https://bugs.debian.org/814096)) that building Neovim against a post-1.0 msgpack, but running it against a pre-1.0 libmsgpackc2.so results in mis-parsing the message pack.

In this case, it's likely due to the use of the new bin types (0xc4) which were reserved in the old spec.  Even though there's not an explicit ABI conflict, should libmsgpackc have had its ABI bumped when the new spec was implemented to prevent these runtime conflicts?

**Comment by redboltz** [comment]
Hi @jamessan, thank you for reporting the issue.

I'm not sure I understand what the problem is. But I can tell you the current situation and history.

* Here is the strategy to introduce the new bin types
  * First, msgpack-* implemented only unpacking functionality for the new bin types. It is mapped to RAW types. It works well with the new bin types.
  * Then, implemented packing functionality for the new bin types.
  * Finally, re-mapped the new bin types to BIN types on unpacking. Old raw types are mapped to the new STR types. It works well with the old raw types.
* On msgpack-c, unpacking 0xc4 has been supported since 0.5.8.
  * This is the commit https://github.com/msgpack/msgpack-c/commit/85b5e1088f74abdee01798be286e2ed953e1124b
* msgpack-c started to support packing the new bin types and re-mapping BIN types on version 1.0.0.
* During those updates, so version of libmsgpackc is not changed. It is always 2.0.0.
* msgpack::object layouts are the same between old RAW, new BIN, and new STR. See https://github.com/msgpack/msgpack-c/blob/cpp-0.5/src/msgpack/object.h#L60 https://github.com/msgpack/msgpack-c/blob/cpp-1.0/include/msgpack/object.h#L70

**Comment by jamessan** [comment]
Neovim was built against msgpack-c 1.4.0 but is running with libmsgpackc2 from a build of msgpack-c 0.5.7.

With this combination, msgpack-c isn't able to unpack what it packed.  As an example, here's the packed file:

```
% xxd ~/.local/share/nvim/shada/main.shada
00000000: 01ce 56be a3ad 4785 a967 656e 6572 6174  ..V...G..generat
00000010: 6f72 c404 6e76 696d a776 6572 7369 6f6e  or..nvim.version
00000020: c40a 4e56 494d 2030 2e31 2e31 a96d 6178  ..NVIM 0.1.1.max
00000030: 5f6b 6279 7465 0aa3 7069 64cd 77e5 a865  _kbyte..pid.w..e
00000040: 6e63 6f64 696e 67c4 0575 7466 2d38 0300  ncoding..utf-8..
00000050: 0391 c400 04ce 56be a3ad 0592 00c4 0171  ......V........q
```

When Neovim starts and tries to unpack that, it gets a `MSGPACK_UNPACK_CONTINUE` error from msgpack_unpack_next at byte 81, even though the same configuration is what generated the file.

Maybe I just need to change the Debian packaging for msgpack-c to declare a higher minimum library version for any of the APIs that deal with the object types, since the semantics changed.  It sounds like I'm running into the same issue as #67, which basically has the same suggestion.

**Comment by redboltz** [comment]
> Maybe I just need to change the Debian packaging for msgpack-c to declare a higher minimum library version for any of the APIs that deal with the object types, since the semantics changed.

Yes, the version is 0.5.8. See https://github.com/msgpack/msgpack-c/releases/tag/cpp-0.5.8. I hope the Debian will contain the version 1.4.0 in the future, and I will support :)

**Comment by jamessan** [comment]
After investigating more, I've bumped the minimum version for functions that deal with msgpack_object and msgpack_unpacked to 1.0.0, since their behavior depends on the object types enum and that was last modified in d70c44b7.

Thanks for hearing me out. :)

> I hope the Debian will contain the version 1.4.0 in the future

It's already in experimental.  I just need to plan the transition into unstable, since a number of packages which use it fail to build with the newer version.

**Comment by redboltz** [comment]
> After investigating more, I've bumped the minimum version for functions that deal with msgpack_object and msgpack_unpacked to 1.0.0, since their behavior depends on the object types enum and that was last modified in d70c44b.

The version 0.5.8 can unpack the new bin types but cannot pack. The version 1.0.0 can both. It is the youngest version that fully support new bin types. However, version 1.0.0 is problematic. See https://github.com/msgpack/msgpack-c/wiki#important If you need the youngest version that fully support the new bin types, please use https://github.com/msgpack/msgpack-c/releases/tag/cpp-1.1.0.
