### ISSUE TITLE
Does someone like me think it'll be great to have a nicer reference document?

### ISSUE THREAD

**Issue by Asu4ni** [msgpack/msgpack-c#454]
I think it'll be great for beginner like me to have a nicer reference, which describe all the classes, templates, and functions in details. One which looks like [cppreference.com](http://en.cppreference.com/) or [cplusplus.com](www.cplusplus.com/reference) would be great.
What do you think? Is there already plans to do that? Or we should start doing it?

**Comment by redboltz** [comment]
We have wiki pages https://github.com/msgpack/msgpack-c/wiki
It is not a complete reference. 

In order to create a reference, execute `make doxygen`. It is not complete so far, pull requests that adds doxygen comments are welcome. I have a plan to create and push `gh-pages` branch that contains documents created by `make doxygen`.

**Comment by redboltz** [comment]
I just pushed the `gh-pages` branch that contains doxygen generated documents:
http://c.msgpack.org/

**Comment by Asu4ni** [comment]
@redboltz That's great!! But is there an easy way for new comer to find that page?
Because when I just started to use the library, I only found the wiki page here, which was not very helpful. It'll be great to have pages like what you post, but I hope it would be easier for beginner to discover.
And by the way, how can I contribute to that page? thanks

**Comment by redboltz** [comment]
@Asu4ni , I will add the link to http://c.msgpack.org/ on README.md and the top of https://github.com/msgpack/msgpack-c/wiki
I think that it makes easier to find the page http://c.msgpack.org/

The msgpack-c documentation started with the wiki page. After I added http://c.msgpack.org/ , there are two places to place documents. I'm not sure what the best way to use both. I think that http://c.msgpack.org/ is for the refenrece and the wiki is for other documents, so far.

> And by the way, how can I contribute to that page?

In order to add doxygen documents, do the following steps:

1. Create a new branch based on `master` branch.
2. Add doxygen comment such as https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/unpack_decl.hpp#L211
3. Create a pull request

Then, I review and merge it.

In order to add gh-pages documents,

1. Create a new branch based on `gh-pages` branch.
2. Edit the created branch.
3. Create a pull request for `gh-pages` (not for `master`)

Then, I review and merge it.

Any ideas?

**Comment by Asu4ni** [comment]
Thanks for help! I'll try to dig into it when I'm free.
My last question is that is there any connection between the gh-page and doxygen comments?
like, will the reference page be updated if there are some new doxygen comments added?
Thanks again for your helping.

**Comment by redboltz** [comment]
> My last question is that is there any connection between the gh-page and doxygen comments?
> like, will the reference page be updated if there are some new doxygen comments added?

No, so far. They are just two branches on the same repository. That means we need to do some manual work :(
I guess that someone already do the similar thing by more sophisticated (automated) way. But I don't have a much time to study the way. Helps are welcome :)
