### ISSUE TITLE
how to unpack partial data ?

### ISSUE THREAD

**Issue by edsiper** [msgpack/msgpack-c#459]
I need to handle a stream of data (msgpack), imagine a big array with thousands of elements, so on each read(2) call in my network server I want to start consuming the array elements that are completed. The problem is that I cannot find a way to accomplish this as everytime I try to unpack the API complains that more data is required (MSGPACK_UNPACK_CONTINUE).

Would you please advice how to unpack partial data without store all buffer at once ?

**Comment by redboltz** [comment]
There is no way to unpack partial data, so far. But I'm implementing SAX style unpacking API. See #418. It would meet your needs. I will send the PR when I finished implementing.

There are some workaround but they are not elegant.

1. If sender can be  modified, change sender data format from ARRAY to the sequence of msgpack objects. 
2. If you can know the header of the array, skip the array header, and then unpack each objects.
3. If your goal is load distribution and don't need to access unpacked objects, use msgpack::unpacker. When you call msgpack::unpacker::next(), parsing process is done internally. But you can't access partial unpacked objects.

**Comment by redboltz** [comment]
I merged parse APIs.
https://github.com/msgpack/msgpack-c/commit/d15d9220ff109679064429d3b0639fcaac26990b

You can use a visitor with parse API.
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_visitor

If you only want to access partial data, you can use it. If you also want to access full parsed msgpack object, it is pretty difficult. First, inherit `msgpack::detail::create_object_visitor` https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v2/unpack.hpp#L84, and then define member functions you want to access partial data, in the member function, call base class's member function.

**Comment by redboltz** [comment]
I will close the issue. If you have any comments, please post here :)

**Comment by TimSC** [comment]
@redboltz I'm also trying to decode a TCP stream. I'm having a problem with packets being merged so I potentially have one and a half msgpacks in my buffer. I need to detect where the first (complete) msgpack ends and the second (partial packet) begins. With v2.1.5, msgpack::unpack throws an unpack_error when it has one and a half packets. I might expect it to properly decode the first packet and set the offset parameter, so I can manage my input buffer. Have you though about this possibility?

(When I have two complete packets, it properly decodes.)

**Comment by redboltz** [comment]
@TimSC , please use `msgpack::unpacker` instead of `msgpack::unpack()`.

See
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker#msgpack-controls-a-buffer

Here is TCP send/receive example using `boost::asio`.
https://github.com/msgpack/msgpack-c/blob/master/example/boost/asio_send_recv.cpp

**NOTE:**

If you want to unpack partial MessagePack formatted data, the library need to store the partially decoded data to somewhere. And use it the next unpack. The function interface `msgpack::unpack()` doesn't meet such usecases. We need some area to store the partial decoded data, and ***class*** is appropriate for that instead of **function**. That's why you need to use `msgpack::unpacker`.

**Comment by TimSC** [comment]
@redboltz Thx, that works perfectly! (I read the docs but I became confused between unpacker and unpack.)
