### ISSUE TITLE
no manpages / docs

### ISSUE THREAD

**Issue by haneefmubarak** [msgpack/msgpack-c#48]
manpages aren't all that difficult to do anymore, especially with tools like `md2man` and they provide an excellent form of documentation. I would write them myself, except that I don't know what a good amount of the functions do and can't find any documentation.

If some documentation on each of the functions (in C) exist somewhere, I would love to begin writing manpages on a separate branch (maybe `man` :smile_cat: ).

**Comment by redboltz** [comment]
We have the wiki now. See https://github.com/msgpack/msgpack-c/wiki
I need to write some pictures so I choose wiki.

**Comment by KennethWilke** [comment]
:+1: All the documentation for msgpack in the wiki is for C++, I'm finding msgpack quite painful to use in good ol' fashioned C.

**Comment by redboltz** [comment]
Hi @KennethWilke, thank you for the comment. I understand that the documentation of the C part of msgpack-c is not enough. So far, only some examples exist...

> I'm now trying to understand if there's a reference counting mechanism I need to appease, or if I just need to keep my unpacked object hanging around for the life cycle of the .data member of that structure.

I think that the following example is helpful in your usecase:
https://github.com/msgpack/msgpack-c/blob/master/example/c/lib_buffer_unpack.c

Using msgpack_unpacker and msgpack_unpacked makes easier to manage object's lifetime.


I also introduce in detail about msgpack-c internal data structure and lifetime management mechanism.
See
https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_object might help understanding. That is a part of C++ documentation but C version has the same concept.

msgpack objects are constructed on the memory pool named zone. So you need to manage zone's lifetime. It's a basic concept. In addition, when msgpack packet contains STR, BIN, and EXT, msgpack object refer to the buffer. So that means when received buffer is deallocated, msgpack object points to dangling object. To solve this problem, there are two approaches in C version. (C++ version provides more sophisticated approach.)

The first approach is using msgpack_unpacker and msgpack_unpacked. Receive buffer is managed by msgpack_unpacker. They manage well objects, zone, and buffer's lifetime. That achieves zero copy deserialization. The second approach is using msgpack::unpack(). In this case, you need to manage received buffer by yourself. When msgpack object has STR, BIN, or EXT, they point to received buffer. The simple approach is memcpy. You can get STR, BIN, or EXT's pointer and size. You can copy msgpack object(STR, BIN, or EXT) to your application object using that information. This approach requires memcpy.

**Comment by redboltz** [comment]
Just started writing C documentation.
https://github.com/msgpack/msgpack-c/wiki/v1_1_c_overview

**Comment by redboltz** [comment]
I have written C documentation. I think that it covers typical use cases.
https://github.com/msgpack/msgpack-c/wiki/v1_1_c_overview

**Comment by redboltz** [comment]
I close the issue. Please reopen it if there are any problems.
