### ISSUE TITLE
Streaming unpack array?

### ISSUE THREAD

**Issue by bluescarni** [msgpack/msgpack-c#509]
I have just started using msgpack, so apologies if this something trivial - but I could not figure it out from the documentation.

The quickstart document shows how it is possible to pack an array in "streaming" fashion:

```c++
msgpack::packer<msgpack::sbuffer> pk(&buffer);
pk.pack_array(3);
pk.pack(std::string("Log message ... 1"));
pk.pack(std::string("Log message ... 2"));
pk.pack(std::string("Log message ... 3"));
```

What I like about this is that it is not necessary to prepare an ``std::vector`` beforehand and feed it to the packer: elements of the array can be added one by one.

I would like to be able to unpack an array in a similar "streaming" fashion, meaning that I would extract the elements of the array one at a time. But I have not been able to do so, so far. What I have been doing instead is something similar.

```c++
// Obtain an object handle in some way.
auto oh = msgpack::unpack(...);
std::vector<std::string> v;
oh.get().convert(v);
```

This works, but the problem here is that I end up allocating a potentially very large vector of strings instead of being able to extract a string at a time from the msgpack array.

My use case here is the following. I have a custom-built data structure (a high-performance unordered set) that gets serialized into msgpack as an array of objects. When I need to deserialize, I would like to be able to extract the serialized elements one by one so that I can just insert them into my unordered set as soon as they are deserialized. In my current approach described above, I first need to extract all elements of the array, and then feed them into my data structure, which requires twice the amount memory.

Am I missing something? Is streaming array unpacking supported and I could not figure out how to use it, or is it not implemented?

**Comment by redboltz** [comment]
@bluescarni , there are some options.

The  first option is `boost::string_ref`. msgpack-c supports `boost::string_ref` and it refers to unpacked buffer. See http://melpon.org/wandbox/permlink/iK7fZukRKGIBZWNb
When you use `msgpack::unpack()`, you need to pass `unpack_reference_func`. It controls reference or copy. See
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker#memory-management

I think that you can use `std::vector<boost::string_ref>` instead of `std::vector<std::string>`. It still requires 
unpacking all at once but data is not copied but referenced.

The second option is `msgpack::type::variant_ref`. It is similar as the first approach. But this approach supports more complicated data structure. See
https://github.com/msgpack/msgpack-c/blob/master/example/boost/msgpack_variant_mapbased.cpp

The above two options avoid copying. But requires unpacking all at once.

The third option is `visitor` interfece. The `visitor` interface provides something like SAX interface. You can handle each msgpack elements step by step during parsing process.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_visitor

**Comment by bluescarni** [comment]
@redboltz Thanks for the reply! The ``variant_ref`` and the ``visitor`` interface look like interesting options. I can also probably live with some overhead regarding memory usage, I just wanted to make sure I was not missing out on something obvious :)

I am closing the bug at this time as there are no issues, thanks again for the help.
