### ISSUE TITLE
lib_buffer_unpack / persistent 'parsed' bytes ?

### ISSUE THREAD

**Issue by edsiper** [msgpack/msgpack-c#514]
I am following the example from lib_buffer_unpack.c file but I cannot manage to accomplish the following: how can I get how many bytes where 'parsed' after a successful return of msgpack_unpacker_next(...) ?.

Looking at definition of _struct msgpack\_unpacker_ the _parsed_ field make sense but it's always set to zero after msgpack_unpacker_next(...) returns with MSGPACK_UNPACK_SUCCESS. I found only a workaround to adding a new field into the structure to keep a persistent _parsed_ values but I am sure it should exists a better way to do it.

use case: upon multiple MSGPACK_UNPACK_SUCCESS for a given buffer, I need to summarized the real bytes used/consumed so I can perform some buffer adjustment in the caller (data is coming from TCP). e.g: incoming buffer have 100 bytes, but only the first 80 are a complete message.

is there a better way to do this ?

**Comment by redboltz** [comment]
> I am following the example from lib_buffer_unpack.c file but I cannot manage to accomplish the following: how can I get how many bytes where 'parsed' after a successful return of msgpack_unpacker_next(...) ?.

Unfortunately, there is no such function, so far.

> Looking at definition of struct msgpack_unpacker the parsed field make sense but it's always set to zero after msgpack_unpacker_next(...) returns with MSGPACK_UNPACK_SUCCESS. I found only a workaround to adding a new field into the structure to keep a persistent parsed values but I am sure it should exists a better way to do it.

Indeed. Your workaround is the simplest solution. 

> use case: upon multiple MSGPACK_UNPACK_SUCCESS for a given buffer, I need to summarized the real bytes used/consumed so I can perform some buffer adjustment in the caller (data is coming from TCP). e.g: incoming buffer have 100 bytes, but only the first 80 are a complete message.

> is there a better way to do this ?

Hmm.. If you don't call `msgpack_unpacker_expand_buffer()`, you can get the parsed size after `msgpack_unpacker_next()` returns with `MSGPACK_UNPACK_SUCCESS` by  `off - COUNTER_SIZE`. However, if you call `msgpack_unpacker_expand_buffer()`, `off` is reset as `COUNTER_SIZE`. So, I believe that the is no way to get total parsed size only from `msgpack_unpacker` except your workaround.

`msgpack_unpacker_expand_buffer()` is called by client, so that means the client has a change to store total parsed size before calling `msgpack_unpacker_expand_buffer()`. How to store the total parsed size? I think that it is pretty complicated. Becase `msgpack_unpacker` could be various status when the client calls `msgpack_unpacker_expand_buffer()`. I think that it requires status management, and client side code (add total parsed size). So I think that your workaround approach is better.

**Comment by edsiper** [comment]
thanks for your response.

should I send a PR with this change or is it too specific for my use case ?

**Comment by redboltz** [comment]
I think that the use case is not too specific. It's a kind of general one. In addition, adding a member variable to msgpack_unpacker is not a big penalty. Because not many msgpack_unpackers are created in general use case, I think. If the target were msgpack_object, we need to be careful.

If you send the PR, it's very helpful. If you do that, please write a test. The test should be located on the following file:
https://github.com/msgpack/msgpack-c/blob/master/test/streaming_c.cpp

By the way, are you using only C part of msgpack-c?

**Comment by edsiper** [comment]
- I will submit a PR. 
- yes, only the C part.

For this change, what sounds better ?

- add just a field into the structure
- add a new API call ?, e.g: 

```C
msgpack_unpack_return 
msgpack_unpacker_next3(msgpack_unpacker* mpac, msgpack_unpacked* result, size_t *p_bytes)
```

**Comment by redboltz** [comment]
Thank you.

I think that I might misunderstand about the problem. I thought that the API is something like as follows:

```cpp
size_t
msgpack_unpacker_total_pased(msgpack_unpacker* mpac);
```

It returns total unpacked size since `msgpack_unpacker` is created. But it is not a good idea because total unpacked size could overflow.

The API you wrote is return (overwrite) p_bytes. 

```cpp
msgpack_unpack_return 
msgpack_unpacker_next3(msgpack_unpacker* mpac, msgpack_unpacked* result, size_t *p_bytes)
```

I have some questions.

* What does p_bytes mean? 
* What happens if the function returns MSGPACK_UNPACK_CONTINUE?

**Comment by edsiper** [comment]
hmm I think that a new function like the proposed one sounds better:

```C
size_t
msgpack_unpacker_total_parsed(msgpack_unpacker* mpac);
```
p_bytes = parsed bytes <- a bit confusing.

I think returning the number of parsed bytes for an object is fine. If the return value is  MSGPACK_UNPACK_CONTINUE it would make sense to set it to the current parsed bytes anyways.

**Comment by redboltz** [comment]
I think that the word `total` seems to be misleading. `msgpack_unpacker_parsed_size()` has already existed. The function is focused on the next buffer, so it returns 0 when `msgpack_unpacker_next()` returns MSGPACK_UNPACK_SUCCESS. In other words, the next buffer is not parsed yet.

The new function we are considering is focused on the previous buffer. See the following image:

```
              msgpack_unpacker_next() returns MSGPACK_UNPACK_SUCCESS
                                                     |
                                        MessagePack1 V MessagePack2
msgpack_unpaker_parsed_size()          |1            2 2
msgpack_unpaker_parse_completed_size() |1            1 2

```

I'm not sure it is the best name but I introduce the name `msgpack_unpaker_parse_completed_size()`.

The next thing I thought is how to implement the function. I found a problem. Let's say the new member variable is `parse_completed`. The problem is when I should clear the `parse_completed` stored in msgpack_unpacker? It's a kind of headache.

The value should be kept after `msgpack_unpacker_next()` returns MSGPACK_UNPACK_SUCCESS. The timing clearing the value is the next `msgpack_unpacker_next()` calling, but how do I know the call is just after returned MSGPACK_UNPACK_SUCCESS.
 
I think that if parsed == 0 in `msgpack_unpacker_next()`, it is an appropriate timing to clear.

**Comment by redboltz** [comment]
I realized that we can implement without adding a new member `parse_completed` to `msgpack_unpacker` if we use the function that you proposed. I renamed the function name. I don't understand what does 3 mean. The number of parameters? Anyway,

```cpp
msgpack_unpack_return 
msgpack_unpacker_next_with_size(msgpack_unpacker* mpac, msgpack_unpacked* result, size_t *p_bytes)
```

Maybe we cal calculate p_bytes from parsed and offset. `parsed` is cleared at https://github.com/msgpack/msgpack-c/blob/master/src/unpack.c#L510 and `msgpack_unpacker_reset()` is called at https://github.com/msgpack/msgpack-c/blob/master/src/unpack.c#L532

We can use the previous `parsed` before calling  `msgpack_unpacker_reset()` in `msgpack_unpacker_next()`.

I think that this approach is better.
