### ISSUE TITLE
#pragma GCC diagnostic’

### ISSUE THREAD

**Issue by jellychen** [msgpack/msgpack-c#536]
Build msgpack with CMake。 but so many warning like this “vector_unsigned_char.hpp:50:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]”。 How can I disable these warning？？

**Comment by redboltz** [comment]
@jellychen , thank you for reporting the issue.

Could you tell me your compiler name and version?

**Comment by roopaligalgali** [comment]
I am facing the same problem, below is the compiler version -
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

**Comment by redboltz** [comment]
@roopaligalgali , thank you for reporting :)

It seems that suppressing `maybe-uninitialized` functionality is introduced since 4.7. (I tested 4.7.3 and 4.7.4).

I will update the following version checking code and other the same checking:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/adaptor/vector_unsigned_char.hpp#L48

**Comment by redboltz** [comment]
@roopaligalgali , I sent the PR to fix the issue. Could you test it?

Here is an instruction:
```
git checkout -b redboltz-fix_536 master
git pull https://github.com/redboltz/msgpack-c.git fix_536
```

**Comment by roopaligalgali** [comment]
It works! Bingo!
Thank you.

**Comment by redboltz** [comment]
The PR has been merged.
Thanks you for testing.
