### ISSUE TITLE
Add support for new types in C++17

### ISSUE THREAD

**Issue by drrlvn** [msgpack/msgpack-c#597]
- `std::optional`
- `std::variant`
- `std::string_view`

These have boost adaptors and need std ones as well.

**Comment by redboltz** [comment]
@spatz , thank you for the comment. 
I think that `std::optional` and `std::string_view` should be supported by the new adaptors.
They are very simple.

However, `std::variant` is a little different. msgpack-c has the types `msgpack::type::variant` and `msgpack::type::variant_ref`. They are implemented using `boost::varinat`. That means msgpack-c doesn't provide `boost::variant` adaptor.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_variant

`msgpack::type::variant` and `msgpack::type::variant_ref` can be implemented using `std::variant` instead of `boost::variant`. I think that it should be provided, and user can switch the implementation using some macro as MSGPACK_VARIANT_USE_STD.

**Comment by redboltz** [comment]
I implemented adaptors for `std::optional` and `std::string_view`. See #607.

`msgpack::type::variant` and `msgpack::type::variant_ref` implemented using `std::variant` is not included in #607.

`msgpack::object` is a composite data structure, so `msgpack::type::variant` reflects the structure. In order to implement it, I use `boost::recursive_wrapper`. However, `std::variant` doesn't have something like `std::recursive_wrapper`. Maybe I need to use the combination of forward declaration and `std::unique_ptr<basic_variant>`. It isn't simple boost to std replacement. I need to study more about it.

So I separated variant support from #607.

**Comment by spatz** [comment]
That's perfectly understandable.
Thank you very much for your responsiveness!

**Comment by redboltz** [comment]
Meged #607.
`std::optional` and `std::string_view` are supported on master.

**Comment by drrlvn** [comment]
Also, `std::byte` should be supported.

**Comment by redboltz** [comment]
`std::byte` is added by #719 .
