### ISSUE TITLE
Is boost a necessary dependency of msgpack-c?

### ISSUE THREAD

**Issue by petten** [msgpack/msgpack-c#606]
I'm in an environment a bit hostile to boost. Before I try to get that (boost) in order for building msgpack, I'd like to know if there is a way not to use boost.

**Comment by redboltz** [comment]
If you don't define `MSGPACK_USE_BOOST`, you don't need boost libraries.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_configure#msgpack_use_boost-since-120

msgpack-c uses Boost.Predef and Boost.Preprocessor as sub-modules. They are header only libraries. msgpack-c contains them.
They are originally from https://github.com/msgpack/msgpack-c/tree/master/external/boost.
But converted as a part of msgpack-c. See https://github.com/msgpack/msgpack-c/tree/master/include/msgpack/predef and https://github.com/msgpack/msgpack-c/tree/master/include/msgpack/preprocessor.
msgpack-c contains converted files. Their namespaces and directly name are replaced, so there is no conflict with existing boost libraries.

**Comment by petten** [comment]
Thanks for your quick reply and detailed explanation.

I was using the `CMakeLists.txt` file, and it was not enough to only set:
```
OPTION (MSGPACK_BOOST "Using boost libraries" OFF)
```

It's also necessary to comment out:
```
FIND_PACKAGE (Boost COMPONENTS chrono context timer system)
```

I'm talking about release 2.1.1. Perhaps I should try 2.1.2.

**Comment by petten** [comment]
Yep, just tried release 2.1.2 (latest).

No need to make any change to `CMakeLists.txt` .

Thank you again.

**Comment by petten** [comment]
Another package that I use in its current state requires release 1.4.2 (it has a difficult time with 2.1.2). So I tried 1.4.2, too. And it was built smoothly just like 2.1.2, without the cmake file being touched.

**Comment by redboltz** [comment]
@petten , thank you for reporting. It seems that all of your questions are solved. If it does, please close the issue.
