### ISSUE TITLE
Support `as<T>` on `object_handle`

### ISSUE THREAD

**Issue by sztomi** [msgpack/msgpack-c#633]
The `as` member template of `object` is a bit clunky to use when the consumer has an `object_handle`:

```cpp
msgpack::object_handle oh = get_some_object_handle();
msgpack::object o = oh.get();
int x = o.as<int>();
// or chaining
int y = oh.get().as<int>();
```

If I understand the semantics correctly, adding an `as` member template to `object_handle` that's basically `return get().as<T>();` should be a zero-cost addition. Would you accept a patch for this?

**Comment by redboltz** [comment]
@sztomi , thank you for the proposal. I considered the proposal.

`msgpack::object` has not only `as()` but also other member functions such as `convert()`.

`msgpack::object_handle` behaves like a smart pointer. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_object

I think that adding `operator->() `and `operator*()` is better approach. Because we don't need to define delegating member functions.

Your example can be written as follows:

```cpp
int y = oh->as<int>();
```

What do you think?

**Comment by sztomi** [comment]
Yes, that makes a lot of sense.

**Comment by sztomi** [comment]
Thanks for merging my PR, I think this can be closed?

**Comment by redboltz** [comment]
Ah, yes. I close it.
