### ISSUE TITLE
adding support for streaming deserialization from Files? 

### ISSUE THREAD

**Issue by Dragoncraft89** [msgpack/msgpack-c#660]
I'm trying to deserialize data located in a binary file using msgpack.
However the file size could get too big to load it all into memory at once, which seems to be required at this point.

I've already tried writing a sbuffer that would allow me to stream but as far as I can see your library needs access to a raw pointer to the data...

It would be great to have this as a feature.

**Comment by redboltz** [comment]
I think that `parser` is helpful.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_visitor#parse-api

This example
https://github.com/msgpack/msgpack-c/blob/master/example/cpp11/socket_stream_example.cpp
might help to understand.

**Comment by Dragoncraft89** [comment]
Looks interesting. Do you have an example for loading user defined structures?

**Comment by redboltz** [comment]
I just wrote the example based on
https://github.com/msgpack/msgpack-c/blob/master/example/boost/asio_send_recv.cpp

This is it.
https://wandbox.org/permlink/5A8PFj4PeFlEddVc

If you treat continuous **complete** message pack data, [unpacker](https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker#msgpack-controls-a-buffer) is good. `unpacker` is implemented using `parser`.

If you treat one huge message pack data like as an array that has million members, `unpacker` is not so useful. Because the `next()` function return true each **complete** message pack data has been processed. In this case, you need to use `parser` directly.

**Comment by Dragoncraft89** [comment]
Thanks I think I could implement this

**Comment by Dragoncraft89** [comment]
I'm sorry that I have to reopen this issue, but I keep getting a strange result when loading from a file.

I wrote a test to determine what maximal size can be easily loaded from a file. I tested loading a ~600 MB file and the object_handle of msgpack::unpack occupied 3 GB of my machine's memory... 

However, the object_handle should free his occupied memory, when it goes out of scope, right?
But it does not seem so, because after I converted the data, I made a little data processing for demonstration purposes and looking into the taskmanager my program's memory is still at 4,0 GB, even after the object_handle went out of scope (I had a { } block around the entire loading phase) and remained at that number until the program terminated.
I tested my program with valgrind, to see if the object_handle was leaked, but valgrind reports that nothing got leaked.

Do you know what could have happened?
I'll try to make a simple example to reproduce my issue

**Comment by Dragoncraft89** [comment]
This is getting weirder:
I cannot reproduce it with a minimal example, but if I remove the object_handle::convert and the object's init function calls, the memory is freed, according to the task manager.

But if one of them is left in the code, the memory is shown as allocated

**Comment by Dragoncraft89** [comment]
I ended up splitting my data structures into smaller chunks, but still can't figure out what happened, so I'll close this permanently now
