### ISSUE TITLE
Trouble deserializing c++ vector

### ISSUE THREAD

**Issue by benlemond** [msgpack/msgpack-c#760]
Is there a recommended way to deserialize (in c#) a message pack object packed in c++ containing a ```std::vector<sometype>```?

I tried ```public List<sometype>``` but that doesn't seem to be working

**Comment by redboltz** [comment]
I don't know how C# version of MessagePack works. msgpack-c's mapping rule is https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#predefined-adaptors.

You need to check C# version of mapping rule.

The process is `C++ type` -> `MessagePack formatter bytes` -> `C# type`

I recommend the following checking process:

1. Check `std::vector<int>` to C# collection type (`List<int>`?)
2. Check C++ `sometype` to C# `sometype`.
3. If above two works as you expected, then `std::vector<sometype>` should be converted to `List<sometype`.

I guess that step 2 could have a problem. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#classes. msgpack-c serializes a user defined class as array by default. But you can modify that behavior. You can use map instead of array using MSGPACK_DEFINE_MAP.

**Comment by benlemond** [comment]
Shoot I just noticed that I out this in mspack-c and intended to put this in msgpack-cli.  Thanks anyways!
