### ISSUE TITLE
Insecure pattern in object.c

### ISSUE THREAD

**Issue by dcleblanc** [msgpack/msgpack-c#774]
There is lots of code like the following:
ret = snprintf(aux_buffer, aux_buffer_size, "\"");
 aux_buffer = aux_buffer + ret;
 aux_buffer_size = aux_buffer_size - ret;

However, according to http://www.cplusplus.com/reference/cstdio/snprintf/, the return from snprintf is:

The number of characters that ***would*** have been written if n had been sufficiently large, not counting the terminating null character.
If an encoding error occurs, a negative number is returned.
Notice that only when this returned value is non-negative and less than n, the string has been completely written.

Emphasis (***) mine - 

So there is failure to properly validate the return from snprintf, which has two failure modes:

1) -1 - the code will now back up aux_buffer to the prior byte, and then increase the remaining size by 1. This is obviously potentially exploitable.

2) ret > aux_buffer_size - now, we increment the aux_buffer pointer beyond the end of the buffer, and aux_buffer_size - ret results in an overflow, which now ends up with aux_buffer_size effectively infinite.

I haven't exhaustively reviewed this code, or even this function, but this seems like a serious error.

**Comment by redboltz** [comment]
It seems that the code in introduced the following commit:

https://github.com/msgpack/msgpack-c/commit/4fa661a63d3c1487107754facb75797849879290#diff-4e46418a61e5218dad7d5eb9c7729ffa
by @smititelu .

I didn't notice about that at that time.

@dcleblanc , I agree with you. This should be fixed.

**Comment by redboltz** [comment]
I think that insert `ret` checking code is a possible fix.

For example:

https://github.com/msgpack/msgpack-c/blob/ce088e7e0a0595d3fb2e47f0e23395b7034292ce/src/objectc.c#L362-L374

```cpp
    case MSGPACK_OBJECT_BIN:
        ret = snprintf(aux_buffer, aux_buffer_size, "\"");
        if (ret == 0 || ret > aus_buffer_size) return 0; /* insert this line */
        aux_buffer = aux_buffer + ret;
        aux_buffer_size = aux_buffer_size - ret;

        ret = msgpack_object_bin_print_buffer(aux_buffer, aux_buffer_size, o.via.bin.ptr, o.via.bin.size);
        if (ret == 0 || ret > aus_buffer_size) return 0; /* insert this line */
        aux_buffer = aux_buffer + ret;
        aux_buffer_size = aux_buffer_size - ret;

        ret = snprintf(aux_buffer, aux_buffer_size, "\"");
        if (ret == 0 || ret > aus_buffer_size) return 0; /* insert this line */
        aux_buffer = aux_buffer + ret;
        aux_buffer_size = aux_buffer_size - ret;
        break;
```

**Comment by dcleblanc** [comment]
Yes, that would be better, but some snprintf implementations return -1 on failure, so I think you want:
if (ret <= 0 || ret > aux_buffer_size) return 0; /* insert this line */

And to not clutter the code, I think I'd make a wrapper inline function.

**Comment by setharnold** [comment]
Has this issue received a CVE number yet?

**Comment by redboltz** [comment]
@setharnold , AFAIK, no it haven't. Your comment is the first one about CVE in msgpack-c.

**Comment by redboltz** [comment]
https://github.com/msgpack/msgpack-c/search?q=CVE&unscoped_q=CVE

**Comment by dcleblanc** [comment]
I never verified that this was exploitable, just that there is a potentially exploitable code flaw. Whether to issue a CVE is up to you to decide.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by setharnold** [comment]
I'm no expert on msgpack-c, so please take my assessment with that caveat in mind.

This issue was reported to Ubuntu with a proof of concept that suggests to me that this is more along the lines of reliability improvements rather than a security fix: the programmer supplies both a buffer and an object, and wants the object written into the buffer.

Perhaps the floating point formats can be surprising: eg `-DBL_MAX` is 317 characters long when serialized with `printf("%d");`. If a program needs to emit `-DBL_MAX` that it reads from a file or another socket, it might then try to serialize this into 32 bytes and be wrong by more than 200.

I'm inclined to say this does not need a CVE without further information. Thoughts?

Thanks

https://bugs.launchpad.net/ubuntu/+source/msgpack-c/+bug/1861448

**Comment by dcleblanc** [comment]
No, that one could cause a buffer overrun. I did not bother to test whether I could exploit this memory corruption, so there’s possibly some mitigating factor, right thing to do was just fix it.

**Comment by 0xddaa** [comment]
Greeting,
I noticed this issue and reported it to Ubuntu bug tracker a few days ago. I am sure this issue is exploitable when receiving untrusted data that packed as a msgpack object.
The return value of `snprintf` can be used to control the index of the buffer, and the attacker can overwrite any memory data behind the buffer.
Some applications which called `msgpack_object_bin_print_buffer` will be affected, such as [fluent-bit](https://github.com/fluent/fluent-bit/blob/5bf04fee8bbd1588204c7b6ca3647a4357d7d20e/plugins/out_slack/slack.c#L185).
This issue should be assigned a CVE number to notice all user fixed the problem.
