### ISSUE TITLE
float leads to unpack error

### ISSUE THREAD

**Issue by RGring** [msgpack/msgpack-c#847]
Hi,
Following situation.
Node1: Packing an object with msgpack in c++ and sending the data.
Node2: Receiving the data and unpacking in python (msgpack.unpackb(payload)). Problem: ValueError gets raised with message "Unpack failed: incomplete input".

I discovered that I only get the Exception, when I pack data with a floating point members. E.g. 

```
class my_class {
public:
    my_class() {} // When you want to convert from msgpack::object to my_class,
                  // my_class should be default constractible.
                  // If you use C++11, you can adapt non-default constructible
                  // classes to msgpack::object.
                  // See https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_adaptor#non-default-constructible-class-support-c11-only
    my_class(std::string const& name, int age):name_(name), age_(age) {}

    friend bool operator==(my_class const& lhs, my_class const& rhs) {
        return lhs.name_ == rhs.name_ && lhs.age_ == rhs.age_;
    }

private:
    std::string name_;
    float age_;

public:
    MSGPACK_DEFINE_MAP(name_, age_);
};
```
I also tried double.
Thanks in advance!

**Comment by redboltz** [comment]
There are two steps in your situation.

1. msgpack-c packs your object into MessagePacke formatted bytes, 
2. msgpack python unpacks from MessagePacke formatted bytes, and creates object.

MessagePack format is defined here:
https://github.com/msgpack/msgpack/blob/master/spec.md

And here is example packing code based on your case:
https://wandbox.org/permlink/EWrcKTR9MbwUOSwP

It seems that packing result is valid MessagePack formatted bytes.

You need to check your packed bytes.
If is is wrong, please let me know. If it is correct, then the problem is in python side.

**Comment by RGring** [comment]
Yes. It seems to be a python problem. Sorry for the inconvenience. I will adress them.
