### ISSUE TITLE
StdTupleConverter is not throwing an error if not enough items are in the array

### ISSUE THREAD

**Issue by bladegreat** [msgpack/msgpack-c#933]
Hi, I want to thank you for this great library. I have encountered some unexpected results from ```msgpack::object::convert``` and want to ask your opinion on if this is an intended behavior or an error. This function declares that ```msgpack::type_error``` would be thrown if object cannot be converted to some Type but it finishes normally when decoding array to tuple when array is smaller than provided tuple.

Short example to reproduce this behavior:  
```cpp
#include <iostream>
#include <utility>
#include <msgpack.hpp>

int main()
{
  // Packing two integers
  std::stringstream sstr;
  msgpack::packer packer(sstr);
  packer.pack_array(2);
  packer.pack(int(1));
  packer.pack(int(2));
  std::string packedData = sstr.str();

  //Trying to unpack three
  auto handle = msgpack::unpack(packedData.data(), packedData.size());
  std::tuple<int, int, int> parsedResult;
  try
  {
    handle->convert(parsedResult);
  }
  catch (msgpack::type_error&)
  {
    std::cout << "Got exception as expected\n";
    return 0;
  }

  std::cout << "Parsed without errors values:"
            << " " << std::get<0>(parsedResult)
            << " " << std::get<1>(parsedResult)
            << " " << std::get<2>(parsedResult) << "\n";
  return 1;
}
```
For now it returns ```1```. I have traced that size mismatch is silently ignored [here](https://github.com/msgpack/msgpack-c/blob/cpp_master/include/msgpack/v1/adaptor/cpp11/tuple.hpp#L96).

**Comment by redboltz** [comment]
Unfortunately, slicing is the behavior by the spec.
See https://github.com/msgpack/msgpack-c/blob/cpp_master/example/cpp03/custom.cpp
If the user defined class is packed ass ARRAY, msgpack-c is sliced the elements that is not mapped to the converted class.
It is expected behavior. 
NOTE: Now msgpack-c has more flexible mapping using MAP see https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#defining-custom-adaptors
But it is originally designed working well with old/new classes with ARRAY.

We can say `std::tuple` is no name class. So `std::tuple` is behaved as this rule.
If you want to strict check, you can define your own tuple using strong typedef idiom and you can write your own adaptor for your custom tuple type that checks the number of members strictly.

**Comment by bladegreat** [comment]
Ok, thank you for response. Closing this issue then.
