### ISSUE TITLE
Reduce stack usage size of unpack.c

### ISSUE THREAD

**Issue by HuyDuongA** [msgpack/msgpack-c#938]
Hello,

In my project, the stack size limits to 512 bytes, and since the **msgpack_unpack()** and **msgpack_unpack_next()** functions use more than 512 bytes, how would you suggest a way to reduce the stack usage size for these two functions?

Here is the full error:
`msgpack-c/unpack.c:618:1: error: stack usage is 1880 bytes [-Werror=stack-usage=]
 msgpack_unpack(const char* data, size_t len, size_t* off,
 ^~~~~~~~~~~~~~`
`msgpack-c/unpack.c:658:1: error: stack usage is 1872 bytes [-Werror=stack-usage=]
 msgpack_unpack_next(msgpack_unpacked* result,
 ^~~~~~~~~~~~~~~~~~~`

**Comment by redboltz** [comment]
I'm not an original C version designer but when I glanced unpacking code of C, the working memory is allocated from the heap not stack. So the stack consumption is caused by something else of the working memory for unpacking.

I'm not sure but setting `MSGPACK_EMBED_STACK_SIZE` is worth trying.

https://github.com/msgpack/msgpack-c/blob/c_master/include/msgpack/unpack_define.h#L24-L26

`MSGPACK_EMBED_STACK_SIZE` is depth of supported msgpack structure. 
Depth means an array of array of array of .... `MSGPACK_EMBED_STACK_SIZE` times.

You can define it as smaller value.

Perhaps `MSGPACK_EMBED_STACK_SIZE` effects only the allocated memory from the heap...

**Comment by HuyDuongA** [comment]
Changing the MSGPACK_EMBED_STACK_SIZE was the solution. Thank you for your help, @redboltz!
