### ISSUE TITLE
Compatibility between msgpack-c and MessagePack-CSharp

### ISSUE THREAD

**Issue by PhilippPaetzold** [msgpack/msgpack-c#947]
Hello,

I want to serialize data between a C++ and C# process and via msgpack-c and MessagePack-CSharp. I am using two simple containers in each language:

// for cpp
```cpp
struct CommandMessage
{
	CommandId commandId {};
	std::vector<int> integers {};
	std::vector<float> floats {};
	std::vector<std::string> strings {};
        std::vector<std::byte> bytes {};
	MSGPACK_DEFINE(commandId, integers, floats, strings, bytes);
};
``` 
// for C#
```csharp
[MessagePackObject]
public class CommandMessage
{
	[Key(0)]
	public CommandId CommandId { get; set; }
	[Key(1)]
	public System.Collections.Generic.List<int> Integers = new ();
	[Key(2)]
	public System.Collections.Generic.List<float> Floats = new ();
	[Key(3)]
	public System.Collections.Generic.List<string> Strings = new ();
	[Key(4)]
	public System.Collections.Generic.List<byte> Bytes = new();
};
```

Both data structures map fine for serialization and deserialization between the two languages / libs. The only problem is with mapping ```std::vector<std::byte>``` to ```List<byte>```. For example, when I encode three bytes 1,2,3 in the vector from C++ they are encoded as ```196,3,1,2,3```. When I do the same with the C# lib it encodes it as: ```147,1,2,3```. Since the other ```vector``` to ```List``` mappings work just fine, I assume it is special here because I use byte / unsigned char which gets serialized as ```bin``` according to the specs of msgpack-c. The MessagePack-CSharp seems to serialize this as any other array / List type.

Is it possible to force array encoding of ```vector<byte>``` for serialization and deserialization with msgpack-c, so I can consume the data with csharp? It would be great, since I am very happy with both libs so far.

**Comment by redboltz** [comment]
You can enforce array using `msgpack::type::array_ref`. `msgpack::type::make_array_ref()` is helper function.
See https://wandbox.org/permlink/wjSmBTtw01DrPmPH
and https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor
This is basic concept.

In your case, `std::vector<char>` is a part of the member variables in your class.
`MSGPACK_DEFINE` macro uses only the default conversion rule.
In order to customize the behavior, you need to use the non intrusive approach instead of `MSGPACK_DEFINE` (intrusive approach)
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#non-intrusive-approach

I implemented only `pack` adaptor to demonstrate how it works. See https://wandbox.org/permlink/6AXDgRPHxylZ41Vv

**Comment by PhilippPaetzold** [comment]
Thank you very much for your quick reply and the great hints and examples. With your help, I can successfully pack my data in the desired format, but I still can not unpack vector<uint8_t>. I would be grateful, if you could take a look at the example I wrote:

https://wandbox.org/permlink/WRv0ltsGfP4VzIM2

**Comment by redboltz** [comment]
I guess that  https://wandbox.org/permlink/pP2AYdIcD4WVXANa would be a solution.

array_ref implementation
https://github.com/msgpack/msgpack-c/blob/cpp_master/include/msgpack/v1/adaptor/array_ref.hpp
test
https://github.com/msgpack/msgpack-c/blob/cpp_master/test/array_ref.cpp

**Comment by PhilippPaetzold** [comment]
I have a working solution. Thank you for all the support and greetings from Germany! I am closing this.
