### ISSUE TITLE
Please, remove the new Boost dependency

### ISSUE THREAD

**Issue by aberaud** [msgpack/msgpack-c#982]
Boost was not required by previous versions of msgpack-c and it was working just fine.

msgpack-c was a very lightweight library, while Boost is huge, and has a super complex and boost-specific build system, even when only using headers.

There seems to be no actual technical reason to require Boost, beyond ease of maintenance for msgpack-c maintainers. But this decision pushes the maintenance cost of the new dependency to every user of the library!

This would add a significant new dependency to our project and significant new short-term and long-term maintenance costs, for a library that is not actually required by msgpack... Please reconsider adding Boost as a dependency.

**Comment by redboltz** [comment]
Since the version 1.2.0 (Sep 2015), msgpack-c has already depended on the Boost Libraries. 
See:
https://github.com/msgpack/msgpack-c/tree/cpp-1.2/include/msgpack/predef
https://github.com/msgpack/msgpack-c/tree/cpp-1.2/include/msgpack/preprocessor

It was a weird approach. Get some version of the Boost Libraries and convert them to msgpack as follows:
https://github.com/msgpack/msgpack-c/blob/cpp-1.2/CMakeLists.txt#L79-L87
It was very difficult to maintain. Boost License allows this approach but this is a kind of **hidden** dependency.
In addition, the converted boost could be the different version of user's boost version.

There were many problems. So we decided to more straight forward approach.
If you don't want to install boost libraries, you don't need to do that.
Just copy boost headers on the specific directory, and add the directory to the include path.
This is almost the same approach as the version 1.2.0 did.
msgpack-c (C++) should work on this approach.
There is one small constraint that you can't do test. But it is the similar as older versions of msgpack-c. That requires gtest 1.7.0 to test.

**Comment by aberaud** [comment]
Thanks a lot for the explanation.
Even though I understand the reasons behind this choice, the previous approach still added significant value for non-Boost users of the library. This value is now gone. Since the library is developed only once and used many times by many people, the total cost of maintaining and using this library skyrocketed.

Given the low number of changes in the project since last year, I still believe it would be reasonably possible to make Boost optional again. Please consider that possibility, as it would truely make life simpler for many users.

In our project, we build a tree of dependencies for many target platforms, like MSVC, Linux, iOS, macOS, Android, so every new dependency means significant long-term maintenance to integrate it and maintain it into our build system.

We used to see msgpack-c as a lightweight, low maintenance cost, and low-risk dependency. All of these assumptions now seem to be false. We probably would not have chosen msgpack as a serialization format to begin with if it required adding Boost to our project (and maintaining it in our build system in the long run just for that serialization library).

**Comment by redboltz** [comment]
I think that you can fork the project and introduce Boost conversion approach again on your fork.
You can use any version of Boost (not too old) as converting source. 
I recommend that if some fix is found is the boost (Predef and Preprosessor), you need to updated your converted source.

Or msgpack-c (C) is not depends on boost. It could be a candidate.

**Comment by redboltz** [comment]
@ygj6 , could you post commet?

**Comment by HorstBaerbel** [comment]
This pulls in the whole of Boost and zlib when using this library from via Conan and there's nothing one do about it (which, agreed, is not fully msgpacks fault). Additionally currently the Conan recipe for boost/1.78.0 is broken (https://github.com/conan-io/conan-center-index/issues/8550), so msgpack-cxx is basically unusable for me...
It would probably be a lot of work, but shouldn't the stdlib be enough? For tests imo [catch2 ](https://github.com/catchorg/Catch2) is better anyway.

**Comment by redboltz** [comment]
It seems that the Conan MSVC boost issue. I guess that is would be solved soon.
Boost is not only for test. See https://github.com/msgpack/msgpack-c/issues/982#issuecomment-920579411

**Comment by redboltz** [comment]
I created #1001 
You can remove boost package dependency using `cmake -DMSGPACK_USE_BOOST=OFF`.
Could someone try this?
However, the implicit dependency of boost is never removed. msgpack-c C++ depends on boost preprocessor and predef as version 3.0.0.

In C++ compiler, when you set `-DMSGPACK_NO_BOOST` option (define `MSGPACK_NO_BOOST` macro), then msgpack-c use the implicit converted boost libraries instead of normal boost libraries.

I have no plan to change the default value `MSGPACK_USE_BOOST` to `OFF`. 
I'm not sure package management system but the package manager can set the cmake option and can create msgpack-c package without boost packeage.

**Comment by aberaud** [comment]
Thanks a lot for your work !

**Comment by redboltz** [comment]
Solved by #1002. msgpack-c implicitly depends on boost even if MSGPACK_NO_BOOST is defined.
