### ISSUE TITLE
object_stringize_visitor::visit_bin() should probably not send the bytes to the stream

### ISSUE THREAD

**Issue by sukidog** [msgpack/msgpack-c#994]
Sending a msgpack obect to a stream likely has an unprintable outcome if the object has a key with a binary object.

The following code:

```
msgpack::object myobject = getobject();
std::cout << myobject;
```
will have an unpleasant result when it gets to the binary field, which likely will have terminal control bytes.

Unless I'm overlooking something, it seems to me we'd want object_stringize_visitor::visit_bin(const char* v, uint32_t size) to do something like

` 
   m_os << "BINARY(" << size << ")";
`

instead of what it currently does.

**Comment by redboltz** [comment]
https://github.com/msgpack/msgpack-c/blob/1f663d121ec602bc96e65b72c47244aa30159135/include/msgpack/v1/object.hpp#L396

object_strigize_visitor EXT and BIN 

https://github.com/msgpack/msgpack-c/blob/1f663d121ec602bc96e65b72c47244aa30159135/include/msgpack/v1/object.hpp#L396

are not well considered, so far.

I think that your proposal could be an good option.
So could you send a PR for refine EXT and BIN stringize with size?

**Comment by sukidog** [comment]
Will do

**Comment by sukidog** [comment]
https://github.com/msgpack/msgpack-c/pull/995

**Comment by redboltz** [comment]
Thanks. 
There are some points to implement:

## Json compatibility

There are some design choice.
The result string of `object_stringize_visitor` is json if we satisfies the following requirement:

1. Don't use BIN
2. Don't use EXT
3. The key of MAP type must be STR

3 is come from json spec.  But now 1 and 2 can be removed if the gotten string is double quoted.
I mean the got value shoule be `"BINARY(5)"` instead of `BINARY(5)`.

## Type naming

I think that `BIN` is better than `BINARY`.
msgpack-c already use `EXT` for stringize. 
The type string respects https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family
So applying the same policy, `BIN` is good name.

## EXT type and size
For BIN size should directly be used as `BIN(10)` on size = 10. It's simple
EXT can be the same but the first byte of `v` is Extension type. 
https://github.com/msgpack/msgpack/blob/master/spec.md#extension-types

When `visit_ext()` is called with size 10, and v[0] is 1,
print `EXT(1,9)` is possible choice. That means Extension type is 1 and 9bytes payload.
Or `EXT(type:1,size:9)`.
If we choose latter, `BIN(10)` should be `BIN(size:10)`.

## Conclusion
I think that for EXT type `"EXT(type1,size:9)"`, and for BIN type `"BIN(size:10)"` is good.
NOTE: EXT type is signed value. So it should print `-1` if the type value is nagative.

**Comment by sukidog** [comment]
That sounds great to me. Let me adjust my PR...
